# GitHub Actions CI/CD Pipeline
# Sistema de Reservas Backend
#
# Este archivo debe colocarse en: .github/workflows/ci.yml

name: CI/CD Pipeline - Sistema de Reservas

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: '18.x'
  MONGODB_VERSION: '7.0'

jobs:
  # ==========================================
  # JOB 1: LINT Y FORMATO
  # ==========================================
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar ESLint
        run: npm run lint || true
        continue-on-error: true

  # ==========================================
  # JOB 2: PRUEBAS UNITARIAS
  # ==========================================
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests unitarios
        run: npm run test:unit
        env:
          NODE_ENV: test
          JWT_SECRET: test_secret_for_ci_pipeline_12345678901234567890

      - name: Subir cobertura
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: unittests
          fail_ci_if_error: false

  # ==========================================
  # JOB 3: PRUEBAS DE INTEGRACIÓN
  # ==========================================
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      mongodb:
        image: mongo:${{ env.MONGODB_VERSION }}
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Esperar MongoDB
        run: |
          for i in {1..30}; do
            if mongosh --eval "db.runCommand({ ping: 1 })" --quiet; then
              echo "MongoDB is ready"
              break
            fi
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Ejecutar tests de integración
        run: npm run test:integration
        env:
          NODE_ENV: test
          MONGO_URI: mongodb://localhost:27017/reservas_test
          JWT_SECRET: test_secret_for_ci_pipeline_12345678901234567890

      - name: Subir cobertura
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: integrationtests
          fail_ci_if_error: false

  # ==========================================
  # JOB 4: ANÁLISIS DE SEGURIDAD
  # ==========================================
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Auditoría de dependencias (npm audit)
        run: npm audit --production || true
        continue-on-error: true

      - name: Escaneo con Snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # ==========================================
  # JOB 5: BUILD
  # ==========================================
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci --production

      - name: Verificar build
        run: node src/app.js &
        env:
          NODE_ENV: production
          MONGO_URI: mongodb://localhost:27017/test
          JWT_SECRET: build_test_secret

      - name: Health check
        run: |
          sleep 5
          curl -f http://localhost:3000/health || exit 1

      - name: Archivar artefactos
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            package.json
            package-lock.json
            src/

  # ==========================================
  # JOB 6: DEPLOY (solo main)
  # ==========================================
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy placeholder
        run: |
          echo "🚀 Deploying to production..."
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          # Aquí iría el deploy real (Railway, Heroku, AWS, etc.)

      - name: Notificar deploy exitoso
        run: echo "✅ Deploy completed successfully!"

  # ==========================================
  # JOB 7: NOTIFICACIONES
  # ==========================================
  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: always()

    steps:
      - name: Resumen del pipeline
        run: |
          echo "📊 CI/CD Pipeline Summary"
          echo "========================="
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          echo "Status: ${{ job.status }}"

      - name: Slack notification (opcional)
        if: failure()
        run: echo "⚠️ Pipeline failed - notification would be sent"
        # uses: 8398a7/action-slack@v3
        # with:
        #   status: failure
        #   webhook_url: ${{ secrets.SLACK_WEBHOOK }}

# ==========================================
# CONFIGURACIÓN DE CACHÉ
# ==========================================
# El caché de npm está configurado automáticamente
# con setup-node@v4 cuando se especifica cache: 'npm'
